name: Build Seatbelt
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: NuGet Restore
      run: nuget restore Seatbelt.sln
    - name: Build Solution
      run: msbuild Seatbelt.sln /p:Configuration=Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Seatbelt-exe
        path: Seatbelt/bin/Release/Seatbelt.exe
