name: Build Obfseat
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Seatbelt
      uses: actions/checkout@v4
      with:
        repository: GhostPack/Seatbelt
        path: Seatbelt
    - name: Checkout InvisibilityCloak
      uses: actions/checkout@v4
      with:
        repository: h4wkst3r/InvisibilityCloak
        path: InvisibilityCloak
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Obfuscate Seatbelt
      run: python InvisibilityCloak/InvisibilityCloak.py -d Seatbelt -n "Obfseat" -m base64
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
    - name: Build Obfseat
      run: |
        # Cherche le fichier solution (.sln) le plus récent (hors dossier InvisibilityCloak)
        $sln = Get-ChildItem -Path . -Filter *.sln -Recurse | Where-Object { $_.DirectoryName -notmatch "InvisibilityCloak" } | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        
        Write-Host "Fichier solution trouvé : $($sln.FullName)"
        
        # On se déplace dans le dossier où se trouve cette solution
        cd $sln.DirectoryName
        
        # On restaure et on compile
        nuget restore $sln.Name
        msbuild $sln.Name /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Obfseat-exe
        # On attrape n'importe quel .exe situé dans un dossier contenant "Release"
        path: '**\Release\*.exe'
